// Implementation file for parser generated by fsyacc
module DCPU16.Assembler.Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "/Users/alanwostenberg/Projects/FSharp/Enigma/Enigma.Assembler.Lib/pars.fsp"



# 10 "/Users/alanwostenberg/Projects/FSharp/Enigma/Enigma.Assembler.Lib/pars.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | COMMA
  | LABEL of (string)
  | ADD
  | SUB
  | MUL
  | DIV
  | SET
  | REG_A
  | REG_B
  | REG_C
  | REG_X
  | REG_Y
  | REG_Z
  | INT of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_COMMA
    | TOKEN_LABEL
    | TOKEN_ADD
    | TOKEN_SUB
    | TOKEN_MUL
    | TOKEN_DIV
    | TOKEN_SET
    | TOKEN_REG_A
    | TOKEN_REG_B
    | TOKEN_REG_C
    | TOKEN_REG_X
    | TOKEN_REG_Y
    | TOKEN_REG_Z
    | TOKEN_INT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | COMMA  -> 1 
  | LABEL _ -> 2 
  | ADD  -> 3 
  | SUB  -> 4 
  | MUL  -> 5 
  | DIV  -> 6 
  | SET  -> 7 
  | REG_A  -> 8 
  | REG_B  -> 9 
  | REG_C  -> 10 
  | REG_X  -> 11 
  | REG_Y  -> 12 
  | REG_Z  -> 13 
  | INT _ -> 14 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_COMMA 
  | 2 -> TOKEN_LABEL 
  | 3 -> TOKEN_ADD 
  | 4 -> TOKEN_SUB 
  | 5 -> TOKEN_MUL 
  | 6 -> TOKEN_DIV 
  | 7 -> TOKEN_SET 
  | 8 -> TOKEN_REG_A 
  | 9 -> TOKEN_REG_B 
  | 10 -> TOKEN_REG_C 
  | 11 -> TOKEN_REG_X 
  | 12 -> TOKEN_REG_Y 
  | 13 -> TOKEN_REG_Z 
  | 14 -> TOKEN_INT 
  | 17 -> TOKEN_end_of_input
  | 15 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 17 
let _fsyacc_tagOfErrorTerminal = 15

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | COMMA  -> "COMMA" 
  | LABEL _ -> "LABEL" 
  | ADD  -> "ADD" 
  | SUB  -> "SUB" 
  | MUL  -> "MUL" 
  | DIV  -> "DIV" 
  | SET  -> "SET" 
  | REG_A  -> "REG_A" 
  | REG_B  -> "REG_B" 
  | REG_C  -> "REG_C" 
  | REG_X  -> "REG_X" 
  | REG_Y  -> "REG_Y" 
  | REG_Z  -> "REG_Z" 
  | INT _ -> "INT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | LABEL _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ADD  -> (null : System.Object) 
  | SUB  -> (null : System.Object) 
  | MUL  -> (null : System.Object) 
  | DIV  -> (null : System.Object) 
  | SET  -> (null : System.Object) 
  | REG_A  -> (null : System.Object) 
  | REG_B  -> (null : System.Object) 
  | REG_C  -> (null : System.Object) 
  | REG_X  -> (null : System.Object) 
  | REG_Y  -> (null : System.Object) 
  | REG_Z  -> (null : System.Object) 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; |]
let _fsyacc_action_rows = 2
let _fsyacc_actionTableElements = [|0us; 16385us; 0us; 49152us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 1us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 0us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; |]
let _fsyacc_reductions ()  =    [| 
# 151 "/Users/alanwostenberg/Projects/FSharp/Enigma/Enigma.Assembler.Lib/pars.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 160 "/Users/alanwostenberg/Projects/FSharp/Enigma/Enigma.Assembler.Lib/pars.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "/Users/alanwostenberg/Projects/FSharp/Enigma/Enigma.Assembler.Lib/pars.fsp"
                                       "Nothing to see here" 
                   )
# 23 "/Users/alanwostenberg/Projects/FSharp/Enigma/Enigma.Assembler.Lib/pars.fsp"
                 : string));
|]
# 171 "/Users/alanwostenberg/Projects/FSharp/Enigma/Enigma.Assembler.Lib/pars.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 18;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : string =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
